package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/z_yongxu/eclipse-workspace/CORBAtest/src/Addition.idl
* Wednesday, June 12, 2019 6:52:44 o'clock PM EDT
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
