package AdditionApp;


/**
* AdditionApp/AdditionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/z_yongxu/eclipse-workspace/CORBAtest/src/Addition.idl
* Thursday, June 27, 2019 9:09:36 o'clock PM EDT
*/

public abstract class AdditionPOA extends org.omg.PortableServer.Servant
 implements AdditionApp.AdditionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("shutdown", new java.lang.Integer (0));
    _methods.put ("sayHello", new java.lang.Integer (1));
    _methods.put ("sayHello2", new java.lang.Integer (2));
    _methods.put ("swapEvent", new java.lang.Integer (3));
    _methods.put ("addEvent", new java.lang.Integer (4));
    _methods.put ("removeEvent", new java.lang.Integer (5));
    _methods.put ("listEventAvailability", new java.lang.Integer (6));
    _methods.put ("bookEvent", new java.lang.Integer (7));
    _methods.put ("cancelEvent", new java.lang.Integer (8));
    _methods.put ("getBookingSchedule", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AdditionApp/Addition/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 1:  // AdditionApp/Addition/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // AdditionApp/Addition/sayHello2
       {
         String $result = null;
         $result = this.sayHello2 ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AdditionApp/Addition/swapEvent
       {
         String customerID = in.read_string ();
         String newEventID = in.read_string ();
         String newEventType = in.read_string ();
         String oldEventID = in.read_string ();
         String oldEventType = in.read_string ();
         boolean $result = false;
         $result = this.swapEvent (customerID, newEventID, newEventType, oldEventID, oldEventType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // AdditionApp/Addition/addEvent
       {
         String managerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         int bookingCapacity = in.read_long ();
         boolean $result = false;
         $result = this.addEvent (managerID, eventID, eventType, bookingCapacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // AdditionApp/Addition/removeEvent
       {
         String ID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         boolean $result = false;
         $result = this.removeEvent (ID, eventID, eventType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // AdditionApp/Addition/listEventAvailability
       {
         String managerID = in.read_string ();
         String eventType = in.read_string ();
         String $result = null;
         $result = this.listEventAvailability (managerID, eventType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // AdditionApp/Addition/bookEvent
       {
         String customerID = in.read_string ();
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         int $result = (int)0;
         $result = this.bookEvent (customerID, eventID, eventType);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // AdditionApp/Addition/cancelEvent
       {
         String eventID = in.read_string ();
         String eventType = in.read_string ();
         String customerID = in.read_string ();
         boolean $result = false;
         $result = this.cancelEvent (eventID, eventType, customerID);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // AdditionApp/Addition/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AdditionApp/Addition:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Addition _this() 
  {
    return AdditionHelper.narrow(
    super._this_object());
  }

  public Addition _this(org.omg.CORBA.ORB orb) 
  {
    return AdditionHelper.narrow(
    super._this_object(orb));
  }


} // class AdditionPOA
